spring.application.name=backend
# 디비
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.username=system
spring.datasource.password=sys
# 서버 포트
server.port=8080
# 디버깅
logging.level.web=info
